name = "Rosmontic"
babel = ["zh", "en-2"]

[contact]
email = "Rosmontis233@hotmail.com"
telegram = "Rosmontis233"
twitter = "Rosmontis233"
github = "Rosmontis2333"

[persona]
pgp = "3CFEFAB3CAC1CC735D67DF41BFFB77088E6643DC"
