name: Generator ROA

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 6 * * 1"

jobs:
  build:
    name: Generate ROA
    if: "github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          path: generated
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          repository: NeoCloud/NeoNetwork-ROA

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          architecture: x64

      - run: pip install -r scripts/requirements.txt

      - run: scripts/generate-roa.sh

      - run: git -C generated diff README.md

      - run: scripts/push-to-roa.sh

      - uses: actions/upload-artifact@v4
        with:
          name: generated
          path: generated
